// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxwtmgxsdfbpktlqegow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4d3RtZ3hzZGZicGt0bHFlZ293Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDU0MjUsImV4cCI6MjA2NTU4MTQyNX0.FmhmFkDxVKt4r5zy2Udh36lReo-bJb4xUPAg4ZPrmhc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);